name: CI

on:
  push:
  release:
    types: [published]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
        with:
          fetch-depth: 50
      - uses: joschi/setup-jdk@v2
        with:
          java-version: '11' # The OpenJDK version to make available on the path
          architecture: 'x64' # defaults to 'x64'
      - name: install requirements
        run: sudo apt-get install ca-certificates-java expect
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install Bazel
        run: |
          npm install --global @bazel/bazelisk
      - name: Install LLVM-11
        run: |
          sudo echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-11 main" >> /etc/apt/sources.list
          sudo echo "deb-src http://apt.llvm.org/stretch/ llvm-toolchain-stretch-11 main" >> /etc/apt/sources.list
          sudo apt-get install libllvm-11-ocaml-dev libllvm11 llvm-11 llvm-11-dev llvm-11-doc llvm-11-examples llvm-11-runtime
          sudo apt-get install clang-11 clang-tools-11 clang-11-doc libclang-common-11-dev libclang-11-dev libclang1-11 clang-format-11 python-clang-11 clangd-11
          sudo apt-get install libfuzzer-11-dev
          sudo apt-get install lldb-11
          sudo apt-get install lld-11
          sudo apt-get install libc++-11-dev libc++abi-11-dev
          sudo apt-get install libomp-11-dev
      - name: run test
        run: bazel test --config=linux //...
